### ISSUE TITLE
Working md-menu example

### ISSUE THREAD

**Issue by treeder** [material-components/material-web#4161]
When I use the example directly [from the code](https://github.com/material-components/material-web/blob/ae913666011ff1f885e9c044a6e842f60b2f906b/menu/menu.ts#L37
), the menu doesn't show up, anyone have a working example they can share?

**Comment by Aworldc** [comment]
Oof. The example is quite vauge and I couldn't understand it either. I hope someone makes documentation for it. Soon.

**Comment by treeder** [comment]
I added all the createRef() stuff from the Lit docs so that example can work and it seems to be doing something with no error, even the "show" attribute shows up in the dev console on `md-menu`, but I can't see it.

**Comment by e111077** [comment]
Heya, sorry that's a bit vague – it's a balance to keep JSdoc concise for such a complex component. We obviously failed here 🤪

We are currently working on our demo / docs site, which should have more complete documentation with the Lit accoutrements that are littered in the JSdoc without explanation.

Here is a working example. There were a few regressions in the latest release that are fixed in the pre.7 release

https://lit.dev/playground/#gist=28fb863d2b2c3387f69b0cf2205a57b2

**Comment by treeder** [comment]
Thanks for the example @e111077 !  Will wait for pre.7 before trying again though.

**Comment by e111077** [comment]
Definitely follow #4141 to get notified

**Comment by treeder** [comment]
Anyone have a non typescript example for md-menu?  Got back to trying it again and still can't get this thing to work (just doesn't show up).

**Comment by e111077** [comment]
@treeder here is a JS approach

https://lit.dev/playground/#gist=c558a9e054344de9495c007a9a6747a2

**Comment by e111077** [comment]
Heads up, the docs for md-menu are on this sprint for me

**Comment by Aworldc** [comment]
woohoo! 🎉🎉🎉

**Comment by treeder** [comment]
Thank you!  🙏 

So finally got it working, but found a strange issue, not sure if there's a setting that fixes this or not (I'll make a new issue if it's not), but if menu is in top right, it opens fine on desktop, moves left to stay on the page:

![image](https://github.com/material-components/material-web/assets/75826/6fa9adfd-deec-4d01-8cb5-a1856329614d)

But on mobile view, it goes off the side:

![image](https://github.com/material-components/material-web/assets/75826/2660b4af-a0c6-4fb6-a51d-7469b371b72b)

**Comment by e111077** [comment]
Odd, it should try to stay in bounds. Have you tried setting menu-corner="START_END"?

**Comment by treeder** [comment]
That did actually work to make it visible on mobile: 

![image](https://github.com/material-components/material-web/assets/75826/ca3e2c08-06f0-4a3a-89ed-46a32f092197)

![image](https://github.com/material-components/material-web/assets/75826/1c2aa307-9a6f-4ba3-83c7-6a12372d476b)

But it's not the positioning I'd prefer. I'm assuming this is a bug then for the default positioning?

**Comment by e111077** [comment]
You might also want to set anchor-corner="END_END"

the default is a default for a button menu. For this you should be customizing the corners

**Comment by asyncLiz** [comment]
Closing since we have menu doc planning tracked internally, it should pop up soon!
