### ISSUE TITLE
Form submission not working for button nor text field

### ISSUE THREAD

**Issue by juanpmarin** [material-components/material-web#4182]
Hi! I've built a small form example:
```
<form method="GET">
  <md-outlined-text-field
    type="text"
    name="name"
  ></md-outlined-text-field>
  <md-filled-button label="Submit" type="submit"></md-filled-button>
</form>
```

But it does not submit in any of the following cases:
- Click the `Submit` button
- Press Enter key when the  text field is focused
- Press Enter key when the button is focused

I understand it's an issue related to shadow dom, but, is there a way to make this work as expected?

**Comment by asyncLiz** [comment]
The button submission will be fixed in an upcoming PR.

Do native input text field submit forms on enter keypress? What happens if there are multiple?

**Comment by rarous** [comment]
@asyncLiz Yes, native input submits form when you press enter. Event if there are multiple. Please, keep native behaviour.

**Comment by Totati** [comment]
[I've created a demo for submit and reset events](https://stackblitz.com/edit/vitejs-vite-zpiysi?file=package.json,main.js,index.html,style.css&terminal=dev)

**Comment by juanpmarin** [comment]
@Totati I've tested your demo in Firefox and Chrome, it does work on Chrome but does not work on Firefox

**Comment by Totati** [comment]
You are right.

**Comment by e111077** [comment]
Updating issue title since it works on chrome

**Comment by austinw-fineart** [comment]
I believe what you're experiencing is a browser quirk when handling forms. Specifically, the Enter key will only submit when either:
- There is only a single input in a form
- There is the presence of an input or button with type=submit

As the Material buttons do not inherit from the HTMLButtonElement it's likely that browsers do not apply the above rules to them.

**Comment by Totati** [comment]
> * There is only a single input in a form
This is not true -> https://stackblitz.com/edit/js-raarmc Both in Chromium and Firefox the form gets submitted

> * There is the presence of an input or button with type=submit
> As the Material buttons do not inherit from the HTMLButtonElement it's likely that browsers do not apply the above rules to them.
Yes, this is true, and they try to come around this by [creating a submit button ](https://github.com/material-components/material-web/blob/main/internal/controller/form-submitter.ts)

**Comment by austinw-fineart** [comment]
> This is not true -> https://stackblitz.com/edit/js-raarmc Both in Chromium and Firefox the form gets submitted

You added a button (type is submit by default) 😛

**Comment by Totati** [comment]
I see, I misunderstand you. A form with a single focused input can be submitted with enter even when there's no submit button. (Didn't know that!) Adding more inputs and the form won't submit anymore.

Will alert
```
<form onsubmit="event.preventDefault(); alert('submitted')">
  <label>Input one <input type="text" name="input1" /></label>
</form>
```
Won't alert
```
<form onsubmit="event.preventDefault(); alert('submitted')">
  <label>Input one <input type="text" name="input1" /></label>
  <label>Input two<input type="text" name="input2" /></label>
</form>
```
Will alert
```
<form onsubmit="event.preventDefault(); alert('submitted')">
  <label>Input one <input type="text" name="input1" /></label>
  <label>Input two<input type="text" name="input2" /></label>
  <button>Submit</button>
</form>
```

**Comment by e111077** [comment]
further investigation here. Seems that the form does submit. It seems in FF the form.submitter value is not being set correctly. Since this issue is solved closing. For submitter issues please see #4949

**Comment by e111077** [comment]
sorry for the hasty close

**Comment by asyncLiz** [comment]
> a button in a `trailing-icon` slot should also submit the form

I don't think I agree from an a11y perspective. Icon buttons contained within a text field should have functionality tied to the text field itself, such as a clear button or a password visibility toggle.

It may be unexpected to have a form submit when using the enter key to trigger the icon button.

**Comment by datvm** [comment]
@asyncLiz that's a good point, thanks. I will fix my app by switching it to a separate button.

Still pressing Enter in the textfield should trigger the form submit. Currently I have to manually handle the textfield's `keydown` event.

**Comment by mai1202** [comment]
Have the bug fixed? It still cannot work on the latest Chrome.

**Comment by therealabdi2** [comment]
Any update or wrokaround for this?

**Comment by asyncLiz** [comment]
The workaround is to add a keypress listener and programmatically submit the form when the enter key is pressed.
